name: CI Pipeline

on: [push, pull_request]

jobs:
  test_node_lts:
    runs-on: ubuntu-latest

    services:
      httpbin:
        image: kennethreitz/httpbin
        ports:
          - 3000:80
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 22.x
      uses: actions/setup-node@v1
      with:
        node-version: 22.x
    - run: npm ci --prefix plugins/redis
    - run: npm ci
    - run: npm run tsc
    - run: npm run buildcjs
    - run: npm link
    - run: npm link node-fetch-cache
      working-directory: plugins/redis
    - run: npm run coverage
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  test_node_other:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.19.0, 18.x, 20.x, 23.x]

    services:
      httpbin:
        image: kennethreitz/httpbin
        ports:
          - 3000:80
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci --prefix plugins/redis
    - run: npm ci
    - run: npm run tsc
    - run: npm run buildcjs
    - run: npm link
    - run: npm link node-fetch-cache
      working-directory: plugins/redis
    - name: Use Node.js Version Under Test
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm test
